### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by RogerDodger8989** [ComputerByte/radarr4k#4]
Hi!

I followed your guide installing a second Radarr. But all i get is an white page saying "404 page not found"

I have Radarr previously installed before this installation. 
I have restarted both Radarr. They both are visible in the toolbar on the left side in my swizzin dashboard and my first radarr works perfectly.

**Comment by ComputerByte** [comment]
Try a ‘sudo systemctl status radarr4k’ and tell me what it says

**Comment by RogerDodger8989** [comment]
It says:
```
● radarr4k.service - Radarr 4K
   Loaded: loaded (/etc/systemd/system/radarr4k.service; enabled; vendor preset:
   Active: active (running) since Thu 2021-04-29 20:13:42 CEST; 15h ago
 Main PID: 357267 (Radarr)
    Tasks: 15 (limit: 4915)
   Memory: 80.9M
   CGroup: /system.slice/radarr4k.service
           └─357267 /opt/Radarr/Radarr -nobrowser --data=/home/dennis800121/.con

Apr 30 11:17:04 Debian-109-buster-64-minimal Radarr[357267]: [Info] RssSyncServi
Apr 30 11:17:04 Debian-109-buster-64-minimal Radarr[357267]: [Warn] FetchAndPars
Apr 30 11:17:04 Debian-109-buster-64-minimal Radarr[357267]: [Info] DownloadDeci
Apr 30 11:17:04 Debian-109-buster-64-minimal Radarr[357267]: [Info] RssSyncServi
Apr 30 11:17:35 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
Apr 30 11:17:35 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
Apr 30 11:17:35 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
Apr 30 11:17:35 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
Apr 30 11:37:49 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
Apr 30 11:37:49 Debian-109-buster-64-minimal Radarr[357267]: SQLite error (5): d
lines 1-19/19 (END)
```

**Comment by ComputerByte** [comment]
I’m assuming you found my guide on discord right? Gimme a ping and let’s get you sorted.

**Comment by RogerDodger8989** [comment]
I found it here: https://github.com/ComputerByte/radarr4k
Do you have a link to discord?

**Comment by ComputerByte** [comment]
Hmm, that SQlite error shouldnt be effecting your radarr running, try:

sudo systemctl stop radarr
sudo systemctl stop radarr4k

wait like 30 seconds

sudo systemctl start radarr
WAIT like 15 seconds
sudo systemctl start radarr4k

then your radarr4k should just be on https://URL.stuff/radarr4k

**Comment by RogerDodger8989** [comment]
nope, same error.

**Comment by ComputerByte** [comment]
Take this invite for the swizzin discord : https://discord.com/invite/2esbu2N

you’ll see me on the right side with the name byte.

**Comment by ComputerByte** [comment]
I added an uninstaller, give that a shot and a fresh install of radarr4k
