### ISSUE TITLE
Swizzin setup

### ISSUE THREAD

**Issue by itrungtrani** [ComputerByte/radarr4k#5]
So I got it up and running. I waited to start normal radarr before radarr4k. i got both instance running. Do I need two instance of rtorrent also? I can't connect to the client with the 4k instance.

**Comment by ComputerByte** [comment]
Shouldn't need to, I have both my radarr + radarr4k to one QB instance

**Comment by ComputerByte** [comment]
![Screen Shot 2021-04-30 at 10 21 41 PM](https://user-images.githubusercontent.com/46009342/116772251-784e8380-aa02-11eb-9008-927416b33ac9.png)

these are my settings that are working just fine, also make sure in Radarr's general settings that:
Certificate Validation - Disabled for Local Addresses

**Comment by itrungtrani** [comment]
Ahhh thank you so much the "also make sure in Radarr's general settings that:
Certificate Validation - Disabled for Local Addresses" this was my issue thank you so much! 😊

**Comment by ComputerByte** [comment]
For anyone having the same issue:

https://docs.swizzin.net/applications/radarr
